[package]
name = "ratatui-glamour"
version = "0.1.1"
edition = "2024"
authors = ["Bo Maryniuk"]
license = "MIT"
readme = "README.md"
description = "Lip Gloss-inspired terminal styling primitives for ratatui"

[dependencies]
crossterm = "0.28.1"
ratatui = { version = "0.30.0", features = ["all-widgets", "serde", "unstable"] }
unicode-width = "0.2.2"

[[example]]
name = "showcase"
path = "examples/showcase.rs"

[[example]]
name = "widgets"
path = "examples/widgets.rs"
